name: Upload Release Assets

on:
  release:
    types: [published]

jobs:
  build_and_upload_assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Zulu JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :dgrv4_Gateway_serv:clean :dgrv4_Gateway_serv:bootJar

      - name: Create release directory
        run: mkdir -p h2-pack/keys

      - name: Copy JAR and other assets
        run: |
          mv dgrv4_Gateway_serv/build/libs/* h2-pack/
          mv dgrv4_Gateway_serv/keys/* h2-pack/keys/
          mv h2-pack/*.jar h2-pack/digirunner.jar

      - name: Zip release assets
        run: |
          zip -r h2-pack.zip h2-pack/

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: h2-pack.zip
          asset_name: h2-pack.zip
          asset_content_type: application/zip