name: Sync Fork from Upstream

on:
  # 每小時 00 分執行一次（UTC）；臺灣時間等於每小時的 08 分
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Fork with Upstream
        uses: AbdulmelikKalkan/sync-fork-upstream@v1.3
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          owner: Frank-Tsai-Tech
          repo: digiRunner-Open-Source
          branch: main
